Cleanup

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,116 +1,116 @@
 name: Release Process
 
 on:
-  push:
-    tags:
-      - '*-v**'
+    push:
+        tags:
+            - '*-v**'
 
 permissions:
-  contents: write
+    contents: write
 
 jobs:
-  release:
-    name: Release-o-matic
-    runs-on: ubuntu-latest
+    release:
+        name: Release-o-matic
+        runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          path: rpgm/foundry
-          fetch-depth: 0 # Fetch depth is required for tag operations
+        steps:
+            - name: Checkout repository
+              uses: actions/checkout@v4
+              with:
+                  path: rpgm/foundry
+                  fetch-depth: 0 # Fetch depth is required for tag operations
 
-      - name: Checkout shared RPGM repo
-        uses: actions/checkout@v4
-        with:
-          repository: RPGM-Tools/rpgm
-          path: rpgm-tools/rpgm
-          token: ${{ secrets.RPGM_CROSS_REPO_READ_TOKEN }}
+            - name: Checkout shared RPGM repo
+              uses: actions/checkout@v4
+              with:
+                  repository: RPGM-Tools/rpgm
+                  path: rpgm-tools/rpgm
+                  token: ${{ secrets.RPGM_CROSS_REPO_READ_TOKEN }}
 
-      - name: Checkout RPGM Tools Forge repo
-        uses: actions/checkout@v4
-        with:
-          repository: RPGM-Tools/rpgm-tools-forge
-          path: rpgm-tools/rpgm-tools-forge
-          token: ${{ secrets.RPGM_CROSS_REPO_READ_TOKEN }}
+            - name: Checkout RPGM Tools Forge repo
+              uses: actions/checkout@v4
+              with:
+                  repository: RPGM-Tools/rpgm-tools-forge
+                  path: rpgm-tools/rpgm-tools-forge
+                  token: ${{ secrets.RPGM_CROSS_REPO_READ_TOKEN }}
 
-      - name: Extract Module Info from Tag
-        id: module_info
-        working-directory: rpgm/foundry
-        run: |
-          TAG_NAME=${{ github.ref_name }}
-          MODULE_ID=$(echo "$TAG_NAME" | cut -d'-' -f1)  # Extract 'forge', 'vault', or 'tome'
-          TAG_VERSION=$(echo "$TAG_NAME" | cut -d'v' -f2)  # Extract '1.2.3'
-          MODULE_NAME=$(jq -r '.title' < ./modules/rpgm-$MODULE_ID/public/module.json)
+            - name: Extract Module Info from Tag
+              id: module_info
+              working-directory: rpgm/foundry
+              run: |
+                  TAG_NAME=${{ github.ref_name }}
+                  MODULE_ID=$(echo "$TAG_NAME" | cut -d'-' -f1)  # Extract 'forge', 'vault', or 'tome'
+                  TAG_VERSION=$(echo "$TAG_NAME" | cut -d'v' -f2)  # Extract '1.2.3'
+                  MODULE_NAME=$(jq -r '.title' < ./modules/rpgm-$MODULE_ID/public/module.json)
 
-          if ! test -d ./modules/rpgm-$MODULE_ID; then
-            echo "Module does not exist!"
-            exit 1
-          fi
+                  if ! test -d ./modules/rpgm-$MODULE_ID; then
+                    echo "Module does not exist!"
+                    exit 1
+                  fi
 
-          echo "module_id=$MODULE_ID" >> $GITHUB_OUTPUT
-          echo "module_name=$MODULE_NAME" >> $GITHUB_OUTPUT
-          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
+                  echo "module_id=$MODULE_ID" >> $GITHUB_OUTPUT
+                  echo "module_name=$MODULE_NAME" >> $GITHUB_OUTPUT
+                  echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
 
-      - name: Get Version from package.json
-        id: version_info
-        working-directory: rpgm/foundry
-        run: | 
-          VERSION=$(jq -r '.version' < ./modules/rpgm-${{ steps.module_info.outputs.module_id }}/package.json)
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
-          if ! test "$VERSION" == "${{ steps.module_info.outputs.tag_version }}"; then
-            echo "Version name is incorrect! Should be $VERSION, is ${{ steps.module_info.outputs.tag_version }}"
-            exit 1
-          fi
+            - name: Get Version from package.json
+              id: version_info
+              working-directory: rpgm/foundry
+              run: |
+                  VERSION=$(jq -r '.version' < ./modules/rpgm-${{ steps.module_info.outputs.module_id }}/package.json)
+                  echo "version=$VERSION" >> $GITHUB_OUTPUT
+                  if ! test "$VERSION" == "${{ steps.module_info.outputs.tag_version }}"; then
+                    echo "Version name is incorrect! Should be $VERSION, is ${{ steps.module_info.outputs.tag_version }}"
+                    exit 1
+                  fi
 
-      - name: Verify release notes exist
-        id: release_notes
-        working-directory: rpgm/foundry
-        run: |
-          RELEASE_NOTES_PATH="./modules/rpgm-${{ steps.module_info.outputs.module_id }}/assets/changelog/v${{ steps.module_info.outputs.tag_version }}.md"
-          if ! test -f "$RELEASE_NOTES_PATH"; then
-            echo "Missing release notes file at $RELEASE_NOTES_PATH"
-            exit 1
-          fi
-          echo "path=$RELEASE_NOTES_PATH" >> $GITHUB_OUTPUT
+            - name: Verify release notes exist
+              id: release_notes
+              working-directory: rpgm/foundry
+              run: |
+                  RELEASE_NOTES_PATH="./modules/rpgm-${{ steps.module_info.outputs.module_id }}/assets/changelog/v${{ steps.module_info.outputs.tag_version }}.md"
+                  if ! test -f "$RELEASE_NOTES_PATH"; then
+                    echo "Missing release notes file at $RELEASE_NOTES_PATH"
+                    exit 1
+                  fi
+                  echo "path=$RELEASE_NOTES_PATH" >> $GITHUB_OUTPUT
 
-      - uses: pnpm/action-setup@v4
-        name: Install pnpm
-        with:
-          version: 10
-          run_install: false
+            - uses: pnpm/action-setup@v4
+              name: Install pnpm
+              with:
+                  version: 10
+                  run_install: false
 
-      - name: Setup Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: 23
-          cache: 'pnpm'
-          cache-dependency-path: rpgm/foundry/pnpm-lock.yaml
+            - name: Setup Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 23
+                  cache: 'pnpm'
+                  cache-dependency-path: rpgm/foundry/pnpm-lock.yaml
 
-      - name: Install Dependencies
-        working-directory: rpgm/foundry
-        run: pnpm install
+            - name: Install Dependencies
+              working-directory: rpgm/foundry
+              run: pnpm install
 
-      - name: Build Project
-        working-directory: rpgm/foundry
-        run: pnpm build
+            - name: Build Project
+              working-directory: rpgm/foundry
+              run: pnpm build
 
-      - name: Zip .dist/ folder
-        working-directory: rpgm/foundry
-        run: (cd modules; for i in *; do VERSION=$(jq -r '.version' < ${i%}/.dist/module.json); (cd ${i%}/.dist; zip -r "../../../${i%}-v$VERSION.zip" *); done)
+            - name: Zip .dist/ folder
+              working-directory: rpgm/foundry
+              run: (cd modules; for i in *; do VERSION=$(jq -r '.version' < ${i%}/.dist/module.json); (cd ${i%}/.dist; zip -r "../../../${i%}-v$VERSION.zip" *); done)
 
-      - name: Copy module.json 
-        working-directory: rpgm/foundry
-        run: (cd modules; for i in *; do cp "${i%}/.dist/module.json" "../$i.json"; done)
+            - name: Copy module.json
+              working-directory: rpgm/foundry
+              run: (cd modules; for i in *; do cp "${i%}/.dist/module.json" "../$i.json"; done)
 
-      - name: Create GitHub Release
-        uses: softprops/action-gh-release@v2
-        with:
-          tag_name: "${{ steps.module_info.outputs.module_id }}-v${{ steps.module_info.outputs.tag_version }}"
-          name: "${{ steps.module_info.outputs.module_name }} v${{ steps.module_info.outputs.tag_version }}"
-          body_path: "rpgm/foundry/${{ steps.release_notes.outputs.path }}"
-          draft: true
-          fail_on_unmatched_files: true
-          files: |
-            rpgm/foundry/rpgm*.zip
-            rpgm/foundry/rpgm*.json
+            - name: Create GitHub Release
+              uses: softprops/action-gh-release@v2
+              with:
+                  tag_name: '${{ steps.module_info.outputs.module_id }}-v${{ steps.module_info.outputs.tag_version }}'
+                  name: '${{ steps.module_info.outputs.module_name }} v${{ steps.module_info.outputs.tag_version }}'
+                  body_path: 'rpgm/foundry/${{ steps.release_notes.outputs.path }}'
+                  draft: true
+                  fail_on_unmatched_files: true
+                  files: |
+                      rpgm/foundry/rpgm*.zip
+                      rpgm/foundry/rpgm*.json
